export { default as Home } from './home/Home';
export { default as About } from './about/About';
export { default as Blog } from './blog/Blog';
export { default as Branding } from './branding/Branding';
export { default as Courses } from './courses/Courses';
export { default as Networks } from './networks/Networks';
export { default as Publications } from './publications/Publications';
export { default as Training } from './training/Training';
export { default as Insight } from './insight/Insight';